# Generated by Django 6.1 on 2026-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=32)),
                ('retail_price', models.FloatField()),
                ('price_observations', models.PositiveIntegerField(default=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geocode_precision', models.CharField(default='city', help_text='How the coordinate was resolved (city centroid, nominatim, ...).', max_length=16)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuelroute_f_latitud_24ebfc_idx'), models.Index(fields=['retail_price'], name='fuelroute_f_retail__70ff7d_idx')],
            },
        ),
    ]
